version: '3.8'

services:
  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: $(username)
      MONGO_INITDB_ROOT_PASSWORD: $(password)
    ports:
      - "27017:27017"
    networks:
      - sevenspace_network

  auth_service:
    build:
      context: ./services/auth_service
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=$(Database_Link)
      - JWT_SECRET_KEY=${SECRET_KEY}
      - JWT_ALGORITHM=${Algorithm}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${Access_Token_Expire_Time}
    depends_on:
      - mongodb
    networks:
      - sevenspace_network

  property_service:
    build:
      context: ./services/property_service
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - REDIS_URL=redis://redis:6379/0
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_ALGORITHM=${JWT_ALGORITHM}
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS_KEY=${MINIO_ROOT_USER}
      - MINIO_SECRET_KEY=${MINIO_ROOT_PASSWORD}
      - MINIO_BUCKET_NAME=${MINIO_BUCKET_NAME}
    depends_on:
      - postgres
      - redis
      - minio
    networks:
      - sevenspace_network

  image_service:
    build:
      context: ./services/image_service
      dockerfile: Dockerfile
    environment:
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS_KEY=${MINIO_ROOT_USER}
      - MINIO_SECRET_KEY=${MINIO_ROOT_PASSWORD}
      - MINIO_BUCKET_NAME=${MINIO_BUCKET_NAME}
    depends_on:
      - minio
    networks:
      - sevenspace_network

  notification_service:
    build:
      context: ./services/notification_service
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - REDIS_URL=redis://redis:6379/0
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_ALGORITHM=${JWT_ALGORITHM}
    depends_on:
      - postgres
      - redis
    networks:
      - sevenspace_network

  api_gateway:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - AUTH_SERVICE_URL=http://auth_service:8000
      - PROPERTY_SERVICE_URL=http://property_service:8000
      - IMAGE_SERVICE_URL=http://image_service:8000
      - NOTIFICATION_SERVICE_URL=http://notification_service:8000
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_ALGORITHM=${JWT_ALGORITHM}
    depends_on:
      - auth_service
      - property_service
      - image_service
      - notification_service
    networks:
      - sevenspace_network

networks:
  sevenspace_network:
    driver: bridge
volumes:
  postgres_data:
  redis_data:
  minio_data: 
