version: '3.8'

services:
  auth_service:
    build:
      context: ./services/auth_service
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    env_file: .env
    environment:
      - link=${Database_Link}
      - Secret_key=${SECRET_KEY}
      - algorithm=${Algorithm}
      - access_token_expire_time=${Access_Token_Expire_Time}
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
    networks:
      - sevenspace_network

  property_service:
    build:
      context: ./services/property_service
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    env_file: .env
    environment:
      - link=${Database_Link}
    networks:
      - sevenspace_network

  image_service:
    build:
      context: ./services/image_service
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    env_file: .env
    environment:
      - cloud_name=${CLOUDINARY_CLOUD_NAME}
      - api_key=${CLOUDINARY_API_KEY}
      - api_secret=${CLOUDINARY_API_SECRET}
    volumes:
      - ./services/image_service:/app
    networks:
      - sevenspace_network

  notification_service:
    build:
      context: ./services/notification_service
      dockerfile: Dockerfile
    ports:
      - "8004:8004"
    env_file: .env
    environment:
      - link=${Database_Link}
      - JWT_SECRET_KEY=${SECRET_KEY}
      - JWT_ALGORITHM=${Algorithm}
      - BREVO_KEY=${Brevo_key}
    networks:
      - sevenspace_network

  api_gateway:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file: .env
    environment:
      - AUTH_SERVICE_URL=http://auth_service:8001
      - PROPERTY_SERVICE_URL=http://property_service:8002
      - IMAGE_SERVICE_URL=http://image_service:8003
      - NOTIFICATION_SERVICE_URL=http://notification_service:8004
      - JWT_SECRET_KEY=${SECRET_KEY}
      - JWT_ALGORITHM=${Algorithm}
    depends_on:
      - auth_service
      - property_service
      - image_service
      - notification_service
    networks:
      - sevenspace_network

networks:
  sevenspace_network:
    driver: bridge